export { VirtualEventsHeader } from "./virtual-events-header"
export { VirtualEventsLayout } from "./virtual-events-layout"
export { VirtualEventsMainBody } from "./virtual-events-main-body"
export { VirtualEventsMainContent } from "./virtual-events-main-content"
export { VirtualEventsScheduleSidebar } from "./virtual-events-schedule-sidebar"
export { VirtualEventsSidebar } from "./virtual-events-sidebar"
export { VirtualEventsVideoPlayer } from "./virtual-events-video-player"
