export interface Section {
  id: string;
  label: string;
  children?: Section[];
}

export interface ComponentSections {
  [key: string]: Section[];
}

export const componentSections: ComponentSections = {
  "guides-styling": [
    { id: "overview", label: "Overview" },
    {
      id: "the-contract",
      label: "The contract",
      children: [
        { id: "tokens", label: "Tokens" },
        { id: "classname", label: "className" },
      ],
    },
    {
      id: "forms",
      label: "Forms",
      children: [{ id: "field-wrapping", label: "Field wrapping" }],
    },
    { id: "layout-wrappers", label: "Layout wrappers" },
  ],
  "guides-choosing-components": [
    { id: "overview", label: "Overview" },
    { id: "actions", label: "Actions" },
    { id: "text-entry", label: "Text entry" },
    { id: "selection", label: "Selection" },
    { id: "files", label: "Files" },
    { id: "overlays", label: "Overlays" },
    { id: "feedback", label: "Feedback" },
    { id: "data", label: "Data display" },
    { id: "indicators", label: "Indicators" },
    { id: "conversation", label: "Conversation" },
    { id: "navigation", label: "Navigation" },
    { id: "layout", label: "Layout" },
  ],
  "guides-recipes": [
    { id: "overview", label: "Overview" },
    {
      id: "page-shell",
      label: "Page shell",
      children: [
        { id: "page-shell-standard", label: "Standard page" },
        { id: "page-shell-inbox", label: "Inbox exception" },
      ],
    },
    {
      id: "forms",
      label: "Forms",
      children: [
        { id: "forms-basic", label: "Basic form" },
        { id: "forms-sizing", label: "Sizing" },
        { id: "forms-validation", label: "Validation" },
        { id: "forms-sectional", label: "Large setup forms" },
      ],
    },
    {
      id: "list-pages",
      label: "List pages",
      children: [{ id: "list-pages-table", label: "Data table stack" }],
    },
    {
      id: "overlays",
      label: "Overlays",
      children: [
        { id: "overlays-choosing", label: "Choosing an overlay" },
        { id: "overlays-triggers", label: "Triggers" },
        { id: "overlays-destructive", label: "Destructive actions" },
      ],
    },
    {
      id: "feedback",
      label: "Feedback",
      children: [
        { id: "feedback-choosing", label: "Choosing feedback" },
        { id: "feedback-loading", label: "Loading states" },
      ],
    },
  ],
  "activity-feed": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "condensed", label: "Condensed" },
    { id: "pagination", label: "Pagination" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-activity-feed", label: "ActivityFeed" },
        { id: "api-activity-feed-entry", label: "ActivityFeedEntry" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "inline-edit": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "sizing", label: "Sizing" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  button: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "default", label: "Default button" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-primary", label: "Primary" },
        { id: "variants-secondary", label: "Secondary" },
        { id: "variants-outline", label: "Outline" },
        { id: "variants-destructive", label: "Destructive" },
        { id: "variants-ghost", label: "Ghost" },
        { id: "variants-ghost-destructive", label: "Ghost destructive" },
      ],
    },
    { id: "disabled", label: "Disabled" },
    { id: "dropdown", label: "Dropdown" },
    { id: "link-button", label: "Link button" },
    { id: "sizes", label: "Sizes" },
    {
      id: "icons",
      label: "Icons",
      children: [
        { id: "icons-left", label: "Icon left" },
        { id: "icons-right", label: "Icon right" },
        { id: "icons-only", label: "Icon only" },
      ],
    },
    { id: "loading", label: "Loading button" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  tooltip: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-provider", label: "Provider" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "positioning", label: "Positioning" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-provider", label: "TooltipProvider" },
        { id: "api-tooltip", label: "Tooltip" },
        { id: "api-trigger", label: "TooltipTrigger" },
        { id: "api-content", label: "TooltipContent" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  accordion: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "default", label: "Default" },
    {
      id: "variants",
      label: "Variants",
      children: [{ id: "variants-sectional", label: "Sectional" }],
    },
    {
      id: "controls",
      label: "Controls",
      children: [
        { id: "controls-closed", label: "Closed" },
        { id: "controls-first-open", label: "First open" },
        { id: "controls-all-open", label: "All open" },
        { id: "controls-multiple", label: "Multiple" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "alert-dialog": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    {
      id: "examples",
      label: "Examples",
      children: [
        { id: "examples-confirm-deletion", label: "Confirm deletion" },
        {
          id: "examples-unsaved-changes",
          label: "Discard changes",
        },
        { id: "examples-confirm-save", label: "Confirm save" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  attachment: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "error-handling", label: "Error handling" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-empty", label: "Empty" },
        { id: "states-uploading", label: "Uploading" },
        { id: "states-error", label: "Error" },
        { id: "states-done", label: "Done" },
      ],
    },
    { id: "customisation", label: "Custom icon" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  badge: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "default", label: "Default badge" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-colours", label: "Colours" },
        { id: "variants-bordered", label: "Bordered" },
        { id: "variants-rounded", label: "Rounded" },
      ],
    },
    { id: "sizes", label: "Sizes" },
    {
      id: "with-icons",
      label: "With icons",
      children: [
        { id: "with-icons-left", label: "Left icon" },
        { id: "with-icons-right", label: "Right icon" },
        { id: "with-icons-both", label: "Both icons" },
      ],
    },
    {
      id: "with-avatar",
      label: "With avatar",
      children: [{ id: "with-avatar-sizes", label: "Avatar sizes" }],
    },
    { id: "dismissible", label: "Dismissible" },
    { id: "notification", label: "Notification indicator" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  bubble: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-default", label: "Default" },
        { id: "variants-secondary", label: "Secondary" },
        { id: "variants-outline", label: "Outline" },
        { id: "variants-ghost", label: "Ghost" },
        { id: "variants-destructive", label: "Destructive" },
      ],
    },
    { id: "alignment", label: "Alignment" },
    { id: "full-width", label: "Full width" },
    { id: "group", label: "Group" },
    { id: "reactions", label: "Reactions" },
    { id: "actions", label: "Actions" },
    { id: "show-more", label: "Show more" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  card: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic example" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-with-header", label: "Card with header" },
        {
          id: "variants-with-header-action",
          label: "Card with header action",
        },
        {
          id: "variants-with-header-tooltip",
          label: "Card with header tooltip",
        },
        { id: "variants-with-footer", label: "Card with footer" },
        {
          id: "variants-with-header-and-footer",
          label: "Card with header and footer",
        },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  checkbox: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "with-description", label: "With description" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-default", label: "Default" },
        { id: "states-checked", label: "Checked" },
        { id: "states-indeterminate", label: "Indeterminate" },
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "checkbox-group", label: "Checkbox group" },
    {
      id: "as-button",
      label: "As button",
      children: [
        { id: "as-button-basic", label: "Basic" },
        { id: "as-button-with-description", label: "With description" },
        { id: "as-button-disabled", label: "Disabled" },
        { id: "as-button-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  dialog: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "footer", label: "Footer" },
    { id: "sizing", label: "Sizing" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-dialog", label: "Dialog" },
        { id: "api-dialog-content", label: "DialogContent" },
        { id: "api-dialog-footer", label: "DialogFooter" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  empty: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "with-icon", label: "With icon" },
    {
      id: "actions",
      label: "Actions",
      children: [
        { id: "actions-single", label: "Single action" },
        { id: "actions-multi", label: "Multi-action" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "emoji-picker": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "custom-trigger", label: "Custom trigger" },
    { id: "tray", label: "Reaction tray" },
    { id: "tray-only", label: "Tray only" },
    {
      id: "positioning",
      label: "Positioning",
      children: [
        { id: "positioning-side", label: "Side" },
        { id: "positioning-align", label: "Align" },
        { id: "positioning-corners", label: "Corners" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  input: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "read-only", label: "Read-only" },
    { id: "required", label: "Required" },
    {
      id: "sizing",
      label: "Sizing",
      children: [
        { id: "sizing-small", label: "Small" },
        { id: "sizing-medium", label: "Medium" },
        { id: "sizing-large", label: "Large" },
      ],
    },
    {
      id: "icons",
      label: "Icons",
      children: [
        { id: "icons-left", label: "Left aligned" },
        { id: "icons-right", label: "Right aligned" },
        { id: "icons-left-and-right", label: "Left and right aligned" },
      ],
    },
    { id: "button", label: "Button" },
    { id: "inline", label: "Inline" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "native-select": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "groups", label: "Groups" },
    { id: "sizing", label: "Sizing" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-invalid", label: "Invalid" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-native-select", label: "NativeSelect" },
        { id: "api-native-select-option", label: "NativeSelectOption" },
        { id: "api-native-select-opt-group", label: "NativeSelectOptGroup" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  popover: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-with-header", label: "With header" },
        { id: "variants-with-footer", label: "With footer" },
        {
          id: "variants-with-header-and-footer",
          label: "With header and footer",
        },
      ],
    },
    { id: "with-form", label: "With form" },
    {
      id: "positioning",
      label: "Positioning",
      children: [
        { id: "positioning-side", label: "Side" },
        { id: "positioning-align", label: "Align" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-popover", label: "Popover" },
        { id: "api-popover-trigger", label: "PopoverTrigger" },
        { id: "api-popover-content", label: "PopoverContent" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  progress: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "progress-bar", label: "Progress bar" },
    { id: "with-value", label: "With value" },
    { id: "with-label", label: "With label" },
    {
      id: "progress-bar-sizes",
      label: "Progress bar sizes",
      children: [
        { id: "progress-bar-sizes-small", label: "Small" },
        { id: "progress-bar-sizes-medium", label: "Medium" },
        { id: "progress-bar-sizes-large", label: "Large" },
      ],
    },
    { id: "progress-colour-bar", label: "Progress colour (bar)" },
    { id: "progress-ring", label: "Progress ring" },
    { id: "with-value-ring", label: "With value (ring)" },
    { id: "with-label-ring", label: "With label (ring)" },
    {
      id: "progress-ring-sizes",
      label: "Progress ring sizes",
      children: [
        { id: "progress-ring-sizes-small", label: "Small" },
        { id: "progress-ring-sizes-medium", label: "Medium" },
        { id: "progress-ring-sizes-large", label: "Large" },
      ],
    },
    { id: "progress-colour-ring", label: "Progress colour (ring)" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "radio-group": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "with-description", label: "With description" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-default", label: "Default" },
        { id: "states-checked", label: "Checked" },
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    {
      id: "as-button",
      label: "As button",
      children: [
        { id: "as-button-basic", label: "Basic" },
        { id: "as-button-with-description", label: "With description" },
        { id: "as-button-disabled", label: "Disabled" },
        { id: "as-button-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-radio-group", label: "RadioGroup" },
        { id: "api-radio-group-item", label: "RadioGroupItem" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  select: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "sizes", label: "Sizes" },
    { id: "groups", label: "Groups" },
    { id: "scrollable", label: "Scrollable" },
    { id: "alignment", label: "Alignment" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-select", label: "Select" },
        { id: "api-trigger", label: "SelectTrigger" },
        { id: "api-value", label: "SelectValue" },
        { id: "api-content", label: "SelectContent" },
        { id: "api-item", label: "SelectItem" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  sheet: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "sides", label: "Sides" },
    { id: "sizes", label: "Sizes" },
    { id: "footer", label: "Footer" },
    { id: "overlay", label: "Overlay" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  toast: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "description", label: "Description" },
    { id: "variants", label: "Variants" },
    { id: "action", label: "Action" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-promise", label: "Promise" },
        { id: "states-loading", label: "Loading" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-toast-manager", label: "Toast manager" },
        { id: "api-toast-options", label: "Toast options" },
        { id: "api-toaster", label: "Toaster" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  spinner: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "sizing", label: "Sizing" },
    {
      id: "combinations",
      label: "Combinations",
      children: [
        { id: "combinations-button", label: "Button" },
        { id: "combinations-badge", label: "Badge" },
        { id: "combinations-input", label: "Input" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "structure-header": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "example", label: "Example" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "examples-breadcrumbs-only", label: "Breadcrumbs only" },
        { id: "examples-actions", label: "Actions" },
        { id: "examples-actions-multiple", label: "Multiple actions" },
        { id: "examples-heading", label: "Heading" },
        { id: "examples-sub-heading", label: "Sub-heading" },
        { id: "examples-tabs", label: "Tabs" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-header", label: "Header" },
        { id: "api-header-breadcrumbs-props", label: "HeaderBreadcrumbsProps" },
        { id: "api-header-breadcrumb-item", label: "HeaderBreadcrumbItem" },
        {
          id: "api-header-favourite-action-props",
          label: "HeaderFavouriteActionProps",
        },
        { id: "api-header-action-props", label: "HeaderActionProps" },
        {
          id: "api-header-secondary-button-action",
          label: "HeaderSecondaryButtonAction",
        },
        {
          id: "api-header-secondary-menu-action",
          label: "HeaderSecondaryMenuAction",
        },
        { id: "api-header-menu-item", label: "HeaderMenuItem" },
        { id: "api-header-tabs-props", label: "HeaderTabsProps" },
        { id: "api-header-tabs-item", label: "HeaderTabsItem" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "structure-app-header": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "example", label: "Example" },
    { id: "status-controls", label: "Status controls" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-header", label: "AppHeader" },
        { id: "api-logo", label: "AppHeaderLogo" },
        { id: "api-actions", label: "AppHeaderActions" },
        { id: "api-account-switcher", label: "AppHeaderAccountSwitcher" },
        { id: "api-controls", label: "AppHeaderControls" },
        { id: "api-user-menu", label: "AppHeaderUserMenu" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "structure-app-sidebar": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "example", label: "Example" },
    {
      id: "navigation-structure",
      label: "Navigation structure",
      children: [
        {
          id: "navigation-structure-favourites",
          label: "Favourites",
        },
        {
          id: "navigation-structure-groups",
          label: "Grouped destinations",
        },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-app-sidebar", label: "AppSidebar" },
        { id: "api-favourites", label: "AppSidebarFavourites" },
        { id: "api-nav", label: "AppSidebarNav" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "structure-container": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "example", label: "Example" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "related", label: "Related" },
  ],
  switch: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "size", label: "Size" },
    {
      id: "label-and-description",
      label: "Label and description",
      children: [
        { id: "label-and-description-label", label: "Label" },
        {
          id: "label-and-description-label-desc",
          label: "Label and description",
        },
        {
          id: "label-and-description-position",
          label: "Label position",
        },
      ],
    },
    {
      id: "state",
      label: "State",
      children: [
        { id: "state-disabled", label: "Disabled" },
        { id: "state-error", label: "Error" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  tabs: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "line-variant", label: "Line variant" },
    { id: "vertical", label: "Vertical" },
    { id: "disabled", label: "Disabled" },
    {
      id: "full-width",
      label: "Full width",
      children: [
        { id: "full-width-default", label: "Default tabs" },
        { id: "full-width-line", label: "Line tabs" },
      ],
    },
    {
      id: "overflow",
      label: "Overflow",
      children: [
        { id: "overflow-default", label: "Default tabs" },
        { id: "overflow-line", label: "Line tabs" },
      ],
    },
    {
      id: "badges",
      label: "Badges",
      children: [
        { id: "badges-default", label: "Default tabs" },
        { id: "badges-line", label: "Line tabs" },
        { id: "badges-vertical", label: "Vertical tabs" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-tabs", label: "Tabs" },
        { id: "api-tabs-list", label: "TabsList" },
        { id: "api-tabs-trigger", label: "TabsTrigger" },
        { id: "api-tabs-content", label: "TabsContent" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  textarea: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "read-only", label: "Read-only" },
    { id: "required", label: "Required" },
    { id: "sizes", label: "Sizes" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  alert: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-destructive", label: "Destructive" },
        { id: "variants-info", label: "Info" },
        { id: "variants-success", label: "Success" },
        { id: "variants-warning", label: "Warning" },
      ],
    },
    {
      id: "icon",
      label: "Icon",
      children: [
        { id: "icon-default", label: "Default icons" },
        { id: "icon-custom", label: "Custom icons" },
      ],
    },
    { id: "action", label: "Action" },
    { id: "dismissible", label: "Dismissible" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  avatar: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "default", label: "Default avatar" },
    { id: "sizes", label: "Sizes" },
    { id: "image", label: "With image" },
    { id: "status", label: "Status" },
    { id: "notification", label: "Notification" },
    { id: "label-only", label: "Label" },
    { id: "label-description", label: "Label and description" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-avatar", label: "Avatar" },
        { id: "api-avatar-image", label: "AvatarImage" },
        { id: "api-avatar-label", label: "AvatarLabel" },
        { id: "api-avatar-description", label: "AvatarDescription" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "avatar-group": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic", label: "Basic example" },
    { id: "with-overflow", label: "With overflow" },
    { id: "sizes", label: "Sizes" },
    { id: "with-tooltips", label: "With tooltips" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  breadcrumb: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Canonical use" },
    { id: "with-overflow", label: "With overflow" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  calendar: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic", label: "Basic example" },
    { id: "date-range", label: "Date range" },
    { id: "month-year", label: "Month and year selector" },
    { id: "booked-dates", label: "Booked dates" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  combobox: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "multiple", label: "Multiple" },
    { id: "with-clear", label: "With clear" },
    { id: "groups", label: "Groups" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  command: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "example", label: "Example" },
    { id: "trigger", label: "Trigger" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-command", label: "Command" },
        { id: "api-command-list", label: "CommandList" },
        { id: "api-command-item", label: "CommandItem" },
        { id: "api-command-dialog", label: "CommandDialog" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "context-menu": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "submenu", label: "Submenu" },
    { id: "shortcuts", label: "Shortcuts" },
    { id: "groups", label: "Groups" },
    { id: "icons", label: "Icons" },
    { id: "checkbox", label: "Checkbox" },
    { id: "radio", label: "Radio" },
    { id: "destructive", label: "Destructive" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-context-menu", label: "ContextMenu" },
        { id: "api-context-menu-content", label: "ContextMenuContent" },
        { id: "api-context-menu-item", label: "ContextMenuItem" },
        { id: "api-context-menu-sub-trigger", label: "ContextMenuSubTrigger" },
        {
          id: "api-context-menu-checkbox-item",
          label: "ContextMenuCheckboxItem",
        },
        { id: "api-context-menu-radio-group", label: "ContextMenuRadioGroup" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "date-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "two-digit-year", label: "2-digit year" },
    { id: "american-format", label: "American format" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "date-picker": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic", label: "Basic" },
    { id: "range", label: "Range picker" },
    { id: "dob", label: "Date of birth" },
    { id: "button-trigger", label: "Button trigger" },
    { id: "with-time", label: "With time" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  direction: [{ id: "overview", label: "Overview" }],
  "dropdown-menu": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "submenu", label: "Submenu" },
    { id: "shortcuts", label: "Shortcuts" },
    { id: "icons", label: "Icons" },
    { id: "avatars", label: "Avatars" },
    { id: "checkbox", label: "Checkbox" },
    { id: "radio-group", label: "Radio group" },
    { id: "destructive", label: "Destructive" },
    { id: "search", label: "Search" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  field: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    {
      id: "composition",
      label: "Composition",
      children: [
        { id: "composition-field", label: "Field" },
        { id: "composition-field-group", label: "Field group" },
        { id: "composition-field-set", label: "Field set" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "help-text", label: "Help text" },
    {
      id: "field-group",
      label: "Field group",
      children: [{ id: "field-group-separator", label: "Separator" }],
    },
    { id: "field-set", label: "Field set" },
    { id: "orientation", label: "Orientation" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
        { id: "states-read-only", label: "Read-only" },
        { id: "states-required", label: "Required" },
      ],
    },
    { id: "validation", label: "Validation" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-field", label: "Field" },
        { id: "api-field-legend", label: "FieldLegend" },
        { id: "api-field-error", label: "FieldError" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  filters: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "search", label: "Search" },
    { id: "sort", label: "Sort" },
    { id: "date-range", label: "Date range" },
    { id: "condensed", label: "Condensed" },
    {
      id: "trigger",
      label: "Trigger",
      children: [
        { id: "trigger-label", label: "Trigger label" },
        { id: "trigger-icon", label: "Trigger icon" },
        { id: "trigger-icon-only", label: "Icon only trigger" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-filter", label: "Filter" },
        { id: "api-filter-category", label: "FilterCategory" },
        { id: "api-sort", label: "Sort" },
        { id: "api-date-range-filter", label: "DateRangeFilter" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "otp-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "separator", label: "Separator" },
    { id: "alphanumeric", label: "Alphanumeric" },
    { id: "length", label: "Length" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-input-otp", label: "InputOTP" },
        { id: "api-input-otp-slot", label: "InputOTPSlot" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  kbd: [{ id: "overview", label: "Overview" }],
  label: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "within-form", label: "Within form" },
    { id: "required-field", label: "Required field" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "number-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "sizes", label: "Sizes" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  pagination: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "navigational", label: "Navigational" },
    { id: "table-pagination", label: "Icon only" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-pagination-link", label: "PaginationLink" },
        { id: "api-pagination-previous", label: "PaginationPrevious" },
        { id: "api-pagination-next", label: "PaginationNext" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "scroll-area": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic", label: "Basic" },
    { id: "horizontal", label: "Horizontal" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-scroll-area", label: "ScrollArea" },
        { id: "api-scroll-bar", label: "ScrollBar" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  separator: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "orientation", label: "Orientation" },
    { id: "list", label: "List" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  table: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "footer", label: "Footer" },
    { id: "hoverable", label: "Hoverable rows" },
    { id: "nested", label: "Nested table" },
    {
      id: "expandable",
      label: "Expandable rows",
      children: [
        { id: "expandable-panel", label: "Panel" },
        { id: "expandable-sibling-rows", label: "Sibling rows" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-table", label: "Table" },
        { id: "api-expandable-row", label: "TableExpandableRow" },
        {
          id: "api-expandable-trigger",
          label: "TableExpandableRowTrigger",
        },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "chat-bubble": [
    { id: "overview", label: "Overview" },
    { id: "basic-example", label: "Basic example" },
    { id: "agent", label: "Agent" },
    {
      id: "status",
      label: "Status",
      children: [
        { id: "status-sent", label: "Sent" },
        { id: "status-delivered", label: "Delivered" },
        { id: "status-read", label: "Read" },
        { id: "status-failed", label: "Failed" },
      ],
    },
    { id: "note", label: "Note" },
    {
      id: "info-popover",
      label: "Info popover",
      children: [
        { id: "info-popover-user-message", label: "User message" },
        { id: "info-popover-agent-message", label: "Agent message" },
      ],
    },
  ],
  "chat-head": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "default", label: "Default" },
    { id: "closed", label: "Closed" },
    { id: "unread-notification", label: "Unread notification" },
    { id: "active-state", label: "Active state" },
    { id: "message-preview", label: "Message preview" },
    { id: "controls", label: "Controls" },
    { id: "keyboard", label: "Keyboard" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "colour-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "sizing",
      label: "Sizing",
      children: [
        { id: "sizing-small", label: "Small" },
        { id: "sizing-medium", label: "Medium" },
        { id: "sizing-large", label: "Large" },
      ],
    },
    { id: "with-default-value", label: "With default value" },
    { id: "controlled-value", label: "Controlled value" },
    { id: "direct-hex-input", label: "Direct HEX input" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "data-table": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "table-headers",
      label: "Table headers",
      children: [
        { id: "sorting", label: "Sorting" },
        { id: "help-text", label: "Help text" },
      ],
    },
    { id: "pagination", label: "Pagination" },
    { id: "mass-actions", label: "Mass actions" },
    { id: "row-actions", label: "Row actions" },
    {
      id: "table-toolbar",
      label: "Table toolbar",
      children: [
        { id: "search", label: "Search" },
        { id: "filters", label: "Filters" },
        { id: "column-toggle", label: "Column toggle" },
      ],
    },
    { id: "multi-line-cells", label: "Multi-line cells" },
    { id: "nested-rows", label: "Nested rows" },
    { id: "full-example", label: "Full example" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "reply-box": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "default", label: "Default" },
    { id: "footer-only", label: "Footer only" },
    { id: "note-mode", label: "Note mode" },
    { id: "textarea", label: "Textarea" },
    { id: "basic", label: "Basic" },
    { id: "basic-actions", label: "Basic with actions" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-reply-box", label: "ReplyBox" },
        { id: "api-content", label: "ReplyBoxContent" },
        { id: "api-header", label: "ReplyBoxHeader" },
        { id: "api-footer", label: "ReplyBoxFooter" },
        {
          id: "api-custom-action",
          label: "ReplyBoxTrayCustomAction",
        },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "typing-indicator": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "named", label: "Named" },
    { id: "with-avatar", label: "With avatar" },
    { id: "presence", label: "Presence" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  marker: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-default", label: "Default" },
        { id: "variants-separator", label: "Separator" },
        { id: "variants-border", label: "Border" },
      ],
    },
    { id: "status", label: "Status" },
    { id: "shimmer", label: "Shimmer" },
    { id: "with-icon", label: "With icon" },
    { id: "links-and-buttons", label: "Links and buttons" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-marker", label: "Marker" },
        { id: "api-marker-content", label: "MarkerContent" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  message: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    {
      id: "variants",
      label: "Variants",
      children: [
        { id: "variants-user", label: "User" },
        { id: "variants-agent", label: "Agent" },
        { id: "variants-ai", label: "AI" },
        { id: "variants-note", label: "Note" },
      ],
    },
    {
      id: "types",
      label: "Types",
      children: [
        { id: "types-inbox", label: "Inbox" },
        { id: "types-chat-widget", label: "Chat widget" },
        { id: "types-live-chat", label: "Live chat" },
      ],
    },
    { id: "full-width", label: "Full width" },
    {
      id: "status",
      label: "Status",
      children: [
        { id: "status-sent", label: "Sent" },
        { id: "status-delivered", label: "Delivered" },
        { id: "status-read", label: "Read" },
        { id: "status-failed", label: "Failed" },
      ],
    },
    { id: "group", label: "Group" },
    {
      id: "info-popover",
      label: "Info popover",
      children: [
        { id: "info-popover-user-message", label: "User message" },
        { id: "info-popover-agent-message", label: "Agent message" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-message", label: "Message" },
        { id: "api-message-meta", label: "MessageMeta" },
        { id: "api-message-ai-actions", label: "MessageAiActions" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "message-scroller": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
        { id: "usage-basic", label: "Basic example" },
      ],
    },
    { id: "anchoring", label: "Anchoring turns" },
    { id: "context", label: "Keeping context visible" },
    { id: "auto-scroll", label: "Following the live edge" },
    { id: "animation", label: "Animating new messages" },
    { id: "scroll-state", label: "Reading scroll state" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        {
          id: "api-message-scroller-provider",
          label: "MessageScrollerProvider",
        },
        {
          id: "api-message-scroller-viewport",
          label: "MessageScrollerViewport",
        },
        { id: "api-message-scroller-item", label: "MessageScrollerItem" },
        { id: "api-message-scroller-button", label: "MessageScrollerButton" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "metric-card": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic", label: "Basic" },
    { id: "trend", label: "Trend" },
    { id: "sparkline", label: "Sparkline" },
    { id: "menu", label: "Options menu" },
    { id: "help", label: "Help tooltip" },
    { id: "detail", label: "Detail" },
    { id: "description", label: "Description" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  charts: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    {
      id: "chart-bar",
      label: "Bar",
      children: [
        { id: "chart-bar-single", label: "Single bar" },
        { id: "chart-bar-multiple", label: "Multiple bar" },
        { id: "chart-bar-stacked", label: "Stacked bar" },
      ],
    },
    {
      id: "chart-line",
      label: "Line",
      children: [
        { id: "chart-line-single", label: "Single line" },
        { id: "chart-line-multiple", label: "Multiple lines" },
        { id: "chart-line-dots", label: "Line with dots" },
      ],
    },
    {
      id: "chart-area",
      label: "Area",
      children: [
        { id: "chart-area-single", label: "Area single" },
        { id: "chart-area-multiple", label: "Area multiple" },
        { id: "chart-area-stacked", label: "Area stacked" },
        { id: "chart-area-gradient", label: "Area gradient" },
      ],
    },
    {
      id: "chart-pie",
      label: "Pie",
      children: [
        { id: "chart-pie-default", label: "Default" },
        { id: "chart-pie-labels", label: "With labels" },
        { id: "chart-pie-donut", label: "Donut" },
        { id: "chart-pie-donut-text", label: "Donut with text" },
      ],
    },
    {
      id: "chart-radar",
      label: "Radar",
      children: [
        { id: "chart-radar-default", label: "Default" },
        { id: "chart-radar-dots", label: "With dots" },
        { id: "chart-radar-lines", label: "Lines" },
        { id: "chart-radar-multiple", label: "Multiple" },
      ],
    },
    {
      id: "chart-radial",
      label: "Radial",
      children: [
        { id: "chart-radial-default", label: "Default" },
        { id: "chart-radial-text", label: "With text" },
        { id: "chart-radial-stacked", label: "Stacked" },
      ],
    },
    { id: "chart-tooltip", label: "Tooltip" },
    { id: "chart-legend", label: "Legend" },
    {
      id: "chart-axis",
      label: "Axis",
      children: [
        { id: "chart-axis-x", label: "X axis" },
        { id: "chart-axis-y", label: "Y axis" },
      ],
    },
    {
      id: "chart-grid",
      label: "Grid",
      children: [
        { id: "chart-grid-x", label: "X axis grid" },
        { id: "chart-grid-y", label: "Y axis grid" },
        { id: "chart-grid-none", label: "No grid" },
      ],
    },
    {
      id: "chart-layout",
      label: "Layout",
      children: [
        { id: "chart-with-header", label: "With header" },
        { id: "chart-with-metric", label: "With metric" },
        {
          id: "chart-with-header-and-metric",
          label: "With header and metric",
        },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "telephone-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "default-country", label: "Default country" },
    { id: "force-international-format", label: "Force international format" },
    { id: "sizes", label: "Sizes" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  search: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "with-clear", label: "With clear" },
    { id: "sizing", label: "Sizing" },
    { id: "disabled", label: "Disabled" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "sensitive-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "sizing", label: "Sizing" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "file-field": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    {
      id: "sizing",
      label: "Sizing",
      children: [
        { id: "sizing-small", label: "Small" },
        { id: "sizing-medium", label: "Medium" },
        { id: "sizing-large", label: "Large" },
      ],
    },
    { id: "required", label: "Required" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "file-tree": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "drop-zone": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "custom-label-description", label: "Custom label and description" },
    {
      id: "states",
      label: "States",
      children: [
        { id: "states-disabled", label: "Disabled" },
        { id: "states-error", label: "Error" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "sortable-list": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "row-actions", label: "Row actions" },
    { id: "nested-example", label: "Nested lists" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  counter: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic", label: "Basic example" },
    {
      id: "sizes",
      label: "Sizes",
      children: [
        { id: "sizes-small", label: "Small" },
        { id: "sizes-medium", label: "Medium" },
        { id: "sizes-large", label: "Large" },
      ],
    },
    { id: "variants", label: "Variants" },
    { id: "overflow", label: "Overflow" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "code-snippet": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "inline", label: "Inline" },
    {
      id: "block",
      label: "Block",
      children: [
        { id: "block-basic", label: "Basic" },
        { id: "block-languages", label: "Supported languages" },
        { id: "block-with-copy", label: "With copy button" },
      ],
    },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  color: [
    { id: "overview", label: "Overview" },
    { id: "base-color", label: "Base colors" },
    {
      id: "primary-colors",
      label: "Primary colors",
      children: [{ id: "color-gray", label: "Gray" }],
    },
    {
      id: "secondary-colors",
      label: "Secondary colors",
      children: [
        { id: "color-red", label: "Red" },
        { id: "color-orange", label: "Orange" },
        { id: "color-yellow", label: "Yellow" },
        { id: "color-emerald", label: "Emerald" },
        { id: "color-blue", label: "Blue" },
        { id: "color-violet", label: "Violet" },
      ],
    },
    { id: "accessibility", label: "Accessibility" },
  ],
  typography: [
    { id: "overview", label: "Overview" },
    {
      id: "font-families",
      label: "Font families",
      children: [
        { id: "satoshi", label: "Satoshi" },
        { id: "geist-mono", label: "Geist Mono" },
      ],
    },
    { id: "weights", label: "Weights" },
    { id: "type-scale", label: "Type scale" },
    { id: "text-elements", label: "Text elements" },
  ],
  spacing: [
    { id: "overview", label: "Overview" },
    { id: "usage", label: "Usage" },
    { id: "spacing-scale", label: "Spacing scale" },
    { id: "spacing-patterns", label: "Spacing patterns" },
  ],
  radius: [
    { id: "overview", label: "Overview" },
    { id: "usage", label: "Usage" },
    { id: "radius-scale", label: "Radius scale" },
  ],
  shadows: [
    { id: "overview", label: "Overview" },
    { id: "usage", label: "Usage" },
    { id: "elevation-scale", label: "Elevation scale" },
  ],
  icons: [
    { id: "overview", label: "Overview" },
    { id: "usage", label: "Usage" },
    { id: "sizing", label: "Sizing" },
    { id: "stroke-width", label: "Stroke width" },
    { id: "colour", label: "Colour" },
    { id: "fill", label: "Fill" },
    { id: "accessibility", label: "Accessibility" },
  ],
  "button-group": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "orientation", label: "Orientation" },
    { id: "sizes", label: "Sizes" },
    { id: "split-action", label: "Split action" },
    { id: "with-input", label: "With input" },
    { id: "with-select", label: "With select" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-button-group", label: "ButtonGroup" },
        { id: "api-button-group-text", label: "ButtonGroupText" },
        { id: "api-button-group-separator", label: "ButtonGroupSeparator" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  "input-group": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    {
      id: "alignment",
      label: "Alignment",
      children: [
        { id: "alignment-block-start", label: "Block start" },
        { id: "alignment-block-end", label: "Block end" },
      ],
    },
    { id: "icon", label: "Icon" },
    { id: "text", label: "Text" },
    { id: "button", label: "Button" },
    { id: "kbd", label: "Kbd" },
    { id: "dropdown", label: "Dropdown" },
    { id: "spinner", label: "Spinner" },
    { id: "sizes", label: "Sizes" },
    { id: "within-form", label: "Within form" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-input-group", label: "InputGroup" },
        { id: "api-input-group-addon", label: "InputGroupAddon" },
        { id: "api-input-group-button", label: "InputGroupButton" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  toggle: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [{ id: "usage-import", label: "Import" }],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "sizes", label: "Sizes" },
    { id: "with-text", label: "With text" },
    { id: "controlled", label: "Controlled" },
    { id: "disabled", label: "Disabled" },
    { id: "do-dont", label: "Do and don’t" },
    { id: "api", label: "API" },
    { id: "related", label: "Related" },
  ],
  "toggle-group": [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "multiple", label: "Multiple selection" },
    { id: "sizes", label: "Sizes" },
    { id: "spacing", label: "Spacing" },
    { id: "vertical", label: "Vertical" },
    { id: "disabled", label: "Disabled" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-toggle-group", label: "ToggleGroup" },
        { id: "api-toggle-group-item", label: "ToggleGroupItem" },
      ],
    },
    { id: "related", label: "Related" },
  ],
  sidebar: [
    { id: "overview", label: "Overview" },
    {
      id: "usage",
      label: "Usage",
      children: [
        { id: "usage-import", label: "Import" },
        { id: "usage-composition", label: "Composition" },
      ],
    },
    { id: "basic-example", label: "Basic example" },
    { id: "collapsed-by-default", label: "Collapsed by default" },
    { id: "sidebar-group", label: "Sidebar group" },
    { id: "sub-menu", label: "Sub-menu" },
    { id: "collapsible-sub-menu", label: "Collapsible sub-menu" },
    { id: "do-dont", label: "Do and don’t" },
    {
      id: "api",
      label: "API",
      children: [
        { id: "api-sidebar-provider", label: "SidebarProvider" },
        { id: "api-sidebar", label: "Sidebar" },
        { id: "api-sidebar-menu-button", label: "SidebarMenuButton" },
        { id: "api-sidebar-menu-action", label: "SidebarMenuAction" },
        { id: "api-sidebar-menu-skeleton", label: "SidebarMenuSkeleton" },
        { id: "api-sidebar-menu-sub-button", label: "SidebarMenuSubButton" },
        { id: "api-use-sidebar", label: "useSidebar" },
      ],
    },
    { id: "related", label: "Related" },
  ],
};
